version: "3.8"
services:
  # ---------------------------------------------
  main_db:
    build: ./main_db
    volumes:
      - ./main_db/data:/var/lib/mysql
      - ./main_db/init_queries:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  # ---------------------------------------------
  ch-server:
    build: ./clickhouse_server
    volumes:
      - ./clickhouse_server/data:/var/lib/clickhouse
      - ./clickhouse_server/logs:/var/log/clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    depends_on:
      main_db:
        condition: service_healthy
